### ISSUE TITLE
Ch. 2 Looking at Units Beyond Just Words

### ISSUE THREAD

**Issue by masalas232** [dgrtwo/tidy-text-mining#56] opened 2019-01-17 23:40 UTC
In the last part of the code (line 301 to 316) I am not able to get the correct result stated in the book, a tibble: 6 x 5. My result is a tibble: 0 x 5. I have copied the code exactly from github to R studio and can't seem to find the issue.

**Comment by juliasilge** [comment] 2019-01-19 21:21
Thanks so much for your interest in the book @masalas232! 🙌 I just stepped through all the code in this chapter and I'm not able to reproduce this issue. Can you try again, and tell me what you have in, say, `tidy_books` when you get to this step? Also, can you make sure you have updated CRAN versions of tidyverse and tidytext?

**Comment by juliasilge** [comment] 2019-03-23 20:42
@masalas232 Let me know if you are able to reproduce this problem again! I'm going to close this issue for now.

**Closed by juliasilge** 2019-03-23 20:42 UTC
